Fido.Web/Areas/Authentication/Controllers/ForgottenPasswordController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Fido.Core;
using Fido.ViewModel.Models.Authentication;
using Fido.Web.Common;

namespace Fido.Web.Areas.Authentication.Controllers
{
    [RequireHttps]
    [AllowAnonymous]
    public class ForgottenPasswordController : BaseController
    {
        public ActionResult Create()
        {
            return Dispatcher.Load<ForgottenPassword>(
                Result: m => View(m));
        }

        [HttpPost]
        public ActionResult Create(ForgottenPassword Model)
        {
            return Dispatcher.Create(
                DataModel: Model,
                SuccessResult: m => RedirectToAction("Create", "Login"),
                InvalidResult: m => View(m));
        }
    }
}

Fido.Web/Areas/Authentication/Views/ForgottenPassword/Create.cshtml
@using Fido.Web.Extensions
@model Fido.ViewModel.Models.Authentication.ForgottenPassword

@{
    Layout = null;
    ViewBag.Title = "Forgotten Password?";
}

<!DOCTYPE HTML PUBLIC "" "">
<html lang="en">
<head>
    <meta content="IE=10.000" http-equiv="X-UA-Compatible">
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @Scripts.Render("~/page.top.scripts")
    @Styles.Render("~/nolayout.styles")
    <link href="~/Content/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" />

    @*<meta name="GENERATOR" content="MSHTML 10.00.9200.17116">*@
</head>
<body>
    <div class="row">
        <div class="col-lg-12">
            @Html.Flash()
        </div>
    </div>

    <div class="container">
        <div class="skd-login">

            @using (Html.BeginForm("Create", "ForgottenPassword", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()

                <div class="row skd-row-sm-offset-3">
                    <div class="col-xs-12 col-sm-6">

                        <h3>@ViewBag.Title</h3>
                        Enter your email address below and click 'Send Reset Password'. We will send you a password
                        reset link, via email, that you will need to follow to reset your password.
                        <span class="skd-spacing"></span>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", @placeholder = "email address", @value = "" })
                        </div>
                        @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })

                        <span class="skd-spacing"></span>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <span class="skd-spacing"></span>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Send Password Reset</button>
                    </div>
                </div>
            }
        </div>
    </div>

    @Scripts.Render("~/page.bottom.scripts")
</body>
</html>