Fido.Web/Areas/Account/Controllers/EmailAddressController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Fido.Core;
using Fido.ViewModel.Models.Account;
using Fido.Web.Common;

namespace Fido.Web.Areas.Account.Controllers
{
    public class EmailAddressController : BaseController
    {
        public ActionResult Create()
        {
            return Dispatcher.Load<EmailAddress>(
                Result: m => PartialView());
        }

        [HttpPost]
        public ActionResult Create(EmailAddress Model)
        {
            return Dispatcher.Create(
                DataModel: Model,
                SuccessResult: m => ModalRedirectToLocal(Url.Action("Index", "Settings", new { Area = "Account" }, null)),
                InvalidResult: m => PartialView(m));
        }

        public ActionResult Confirm(Guid ConfirmationId)
        {
            return Dispatcher.Confirm<EmailAddress>(
                Id: ConfirmationId,
                Result: m => RedirectToAction("Create", "Login", new { Area = "Authentication" }));
        }
    }
}

Fido.Web/Areas/Account/Views/EmailAddress/Create.cshtml
@model Fido.ViewModel.Models.Account.EmailAddress
@using Fido.Web.Extensions

<div id="skd-modal-ajax-wrapper">

    <div class="modal-header">
        <h2>Change Email Address</h2>
        <div class="row">
            <div class="col-xs-12">
                @Html.Flash()
            </div>
        </div>
    </div>

    @using (Ajax.BeginForm("Initiate", "EmailAddress",
        new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = "skd-modal-ajax-wrapper"
        }))
    {
        @Html.AntiForgeryToken()
    
        <div class="modal-body">
            <div class="row skd-row-sm-offset-1">
                <div class="col-sm-10">

                    To change your email address, please provide your new email address below and submit the form. A confirmation email
                    containing a link will be sent to your new email address - you will need to follow the confirmation link in the
                    email to complete the change.
                    <span class="skd-spacing"></span>

                    <span class="skd-spacing"></span>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", @placeholder = "email address", @value = "" })
                    </div>
                    @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <div class="col-xs-6 col-centered">
                <button type="submit" class="btn btn-success btn-circle btn-lg" name="Cmd" value="Save" id="approve-btn">
                    <span><i class="fa fa-check"></i></span>
                </button>
            </div>
            <div class="col-xs-6 col-centered">
                <button type="button" class="btn btn-danger btn-circle btn-lg" data-dismiss="modal">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
    }
</div>