Fido.Web/Areas/Account/Controllers/PasswordController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Fido.Core;
using Fido.ViewModel.Models.Account;
using Fido.Web.Common;

namespace Fido.Web.Areas.Account.Controllers
{
    public class PasswordController : BaseController
    {
        public ActionResult Update()
        {
            return Dispatcher.Load<Password>(
                Result: m => PartialView());
        }

        [HttpPost]
        public ActionResult Update(Password Model)
        {
            return Dispatcher.Update(
                DataModel: Model,
                SuccessResult: m => ModalRedirectToLocal(Url.Action("Index", "Settings")),
                InvalidResult: m => PartialView(m));
        }
    }
}

Fido.Web/Areas/Account/Views/Password/Update.cshtml
@model Fido.ViewModel.Models.Account.Password
@using Fido.Web.Extensions

<div id="skd-modal-ajax-wrapper">

    <div class="modal-header">
        <h2>Change Password</h2>
        <div class="row">
            <div class="col-xs-12">
                @Html.Flash()
            </div>
        </div>
    </div>

    @using (Ajax.BeginForm("Update", "Password",
        new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = "skd-modal-ajax-wrapper"
        }))
    {
        @Html.AntiForgeryToken()
    
        <div class="modal-body">
            <div class="row skd-row-sm-offset-1">
                <div class="col-sm-10">

                    Complete the detail below and click on the ok button at the bottom of the screen to change
                    the password for this account.
                    <span class="skd-spacing"></span>

                    <span class="skd-spacing"></span>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control", @placeholder = "current password", @value = "" })
                    </div>
                    @Html.ValidationMessageFor(m => m.OldPassword, "", new { @class = "text-danger" })

                    <span class="skd-spacing"></span>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control", @placeholder = "new password", @value = "" })
                    </div>
                    @Html.ValidationMessageFor(m => m.NewPassword, "", new { @class = "text-danger" })

                    <span class="skd-spacing"></span>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "confirm password", @value = "" })
                    </div>
                    @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <div class="col-xs-6 col-centered">
                <button type="submit" class="btn btn-success btn-circle btn-lg" name="Cmd" value="Save" id="approve-btn">
                    <span><i class="fa fa-check"></i></span>
                </button>
            </div>
            <div class="col-xs-6 col-centered">
                <button type="button" class="btn btn-danger btn-circle btn-lg" data-dismiss="modal">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
    }
</div>