Fido.Web/Areas/Administration/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Fido.Core;
using Fido.ViewModel;
using Fido.ViewModel.Models.Administration;
using Fido.Web.Common;
using Fido.Web.Binders;

namespace Fido.Web.Areas.Administration.Controllers
{
    public class ActivityController : BaseController
    {
        public ActionResult Index()
        {
            return Dispatcher.Index<ActivityIndex>(
                Result: m => View());
        }

        public ActionResult List(ListOptions ListOptions)
        {
            return Dispatcher.List<ActivityList>(
                IndexOptions: ListOptions,
                Result: m => Json(m, JsonRequestBehavior.AllowGet));
        }

        public ActionResult View(Guid Id)
        {
            return Dispatcher.Load<Activity>(
                Id: Id,
                Result: m => View(m));
        }
    }
}

Fido.Web/Areas/Administration/Views/Activity/ActivityForm.cshtml
@model Fido.ViewModel.Models.Administration.Activity

@*Html.LabelFor(m => m.Area)*@

<div class="row">
    <div class="col-md-6">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-gear"></i></span>
            @Html.TextBoxFor(m => m.Area, new { @class = "form-control disabled", @placeholder = "area", @value = "" })
        </div>
        @Html.ValidationMessageFor(m => m.Area, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-gear"></i></span>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control disabled", @placeholder = "name", @value = "" })
        </div>
        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-fw fa-gear"></i></span>
            @Html.TextBoxFor(m => m.ReadWrite, new { @class = "form-control disabled", @placeholder = "read/write", @value = "" })
        </div>
        @Html.ValidationMessageFor(m => m.ReadWrite, "", new { @class = "text-danger" })
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        Roles
    </div>
    <div class="col-xs-12">
        @Html.ListBoxFor(m => m.SelectedRoles, new SelectList(Model.AllRoles, "Id", "Name"), new { @class = "form-control chosen-select" })
    </div>
</div>

<div class="row">
    @*<div class="col-xs-6 col-centered control-button">
        <button type="submit" class="btn btn-success btn-circle btn-lg" name="Cmd" value="Save">
            <span><i class="fa fa-check"></i></span>
        </button>
    </div>*@
    <div class="col-xs-12 col-centered control-button">
        <a href="@Url.Action("Index", "Activity")">
            <span class="btn btn-danger btn-circle btn-lg"><i class="fa fa-times"></i></span>
        </a>
    </div>
</div>

Fido.Web/Areas/Administration/Views/Activity/Index.cshtml
@* http://www.codeproject.com/Articles/155422/jQuery-DataTables-and-ASP-NET-MVC-Integration-Part *@
@model Fido.ViewModel.Models.Administration.ActivityIndex

@using Fido.Web.Controllers

@{
    ViewBag.Title = "Activities";
}

@*<table id="IndexTable" width="100%" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">*@
<div class="table-responsive">
    <table id="IndexTable" class="display responsive nowrap" cellspacing="0">
        <thead>
            <tr>
                <th>Area</th>
                <th>Name</th>
                <th>Read/Write</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<span class="skd-spacing-large"></span>

@section scripts
{
    <script type="text/javascript">
        var ViewLink = '@(Html.ActionLink("View", "View", "Activity", new { Id = -999 }, null))';
        var AjaxPath = '@(Url.Action("List", "Activity"))';

        $(document).ready(function () {
            $('#IndexTable').dataTable({
                "bAutoWidth": false,
                "responsive": true,
                "bServerSide": true,
                "sAjaxSource": AjaxPath,
                "bProcessing": true,
                "aoColumns": [
                    { "sName": "Area", responsivePriority: 1 },
                    { "sName": "Name", responsivePriority: 2 },
                    { "sName": "ReadWrite", responsivePriority: 3 },
                    {
                        responsivePriority: 3,
                        "sName": "View",
                        "bSearchable": false,
                        "bSortable": false,
                        "mRender": function (value) {
                            return ViewLink.replace("-999", value);
                        }
                    }
                ]
            });
        });
    </script>
}

Fido.Web/Areas/Administration/Views/Activity/View.cshtml
@model Fido.ViewModel.Models.Administration.Activity
@using Fido.ViewModel.Models

@{
    ViewBag.Title = "Update Activity";
}

@using (Html.BeginForm("Update", "Activity", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.Hidden("Id", Model.Id)
    @Html.Hidden("CreatedUtc", Model.CreatedUtc)
    @Html.Hidden("IsNew", Model.IsNew)
    @Html.Hidden("RowVersion", Model.RowVersion)

    <div class="well">
        @Html.Partial("ActivityForm", Model)
    </div>
}